### ISSUE TITLE
Proposition to support i18n with EN and FR

### ISSUE THREAD

**Issue by bbouille** [sh-dv/hat.sh#35]
Hello,

I've a use case with international users, how do you see the activation of i18n in the application ?

I would be happy to contribute with a first version supporting EN and FR, what do you think ?

Thank you.

Ben

**Comment by sh-dv** [comment]
Hello, this issue is reopened because it is something in development now in the [hat.sh Dev branch](https://github.com/sh-dv/hat.sh/tree/dev/).
You are more than welcomed to translate to french language, i made it easy for you, all you have to do is edit the 2 files in the [`locales/fr` directory](https://github.com/sh-dv/hat.sh/tree/dev/locales/fr). 

Also if you want to test it out, you can clone the Dev branch then `npm i && npm run dev`. 
You can also read the translation [guide](https://github.com/sh-dv/hat.sh/tree/dev/locales#readme), although there is no need because i already created the files for you.

Your github account will be credited after the main branch merge.

Regards, 
sh-dv

**Comment by bbouille** [comment]
Hello, thank you for the implementation of this. 
Translation in progress for French and I've a question on these 2 keys, what are there purpose please ?

```
sender_key_loaded: "Sender's public key is loaded, please select the encrypted file.",
after_enc_note_one: "You must share this file along with your public key in order for the recipient to decrypt it.",

```
Currently it's a bit confusing to me.

Thank you.

Ben

**Comment by sh-dv** [comment]
Hello, thank you for your efforts.

Take it easy because the next release is planned for the beginning of next month!
And i am still adding more features.

<br>

> sender_key_loaded: "Sender's public key is loaded, please select the encrypted file.",

For example here : [https://hat.sh/?tab=decryption&publicKey=6BcGXidsmWNE3Bswrlu_Ywn1tqSLazQcex4n57NkXB8](https://hat.sh/?tab=decryption&publicKey=6BcGXidsmWNE3Bswrlu_Ywn1tqSLazQcex4n57NkXB8)

When you send a shareable link

<br>

> after_enc_note_one: "You must share this file along with your public key in order for the recipient to decrypt it.",

You can see this notice when you encrypt a file using public/private keys. (Public key method).

**Comment by sh-dv** [comment]
Dev branch got updated, few words got added to the `en` locale.

**Comment by sh-dv** [comment]
Any updates @bbouille ?

**Comment by bbouille** [comment]
Thank for the update, I check that !
